easy_admin:
    site_name: 'Stage'
    entities:
        Users:
            label: 'Пользователи'
            class: App\Entity\Users
            list:
                fields: ['id', 'email', 'roles']
        Events:
            class: App\Entity\Events
            label: 'События'
            list:
                title: 'События'
                fields: ['id', 'title']
            form:
                fields:
                  - { type: 'tab' , label: 'Основные' }
                  - { property: 'title', label: 'Наименование'}
                  - { property: 'description', label: 'Описание'}
                  - { property: 'image', label: 'Изображение'}
                  - { property: 'duration', label: 'Длительность'}
        Hall:
            class: App\Entity\Hall
            controller: App\Controller\Admin\HallController
            label: 'Залы'
            list:
                title: 'Залы'
                fields: ['id', 'name']
            form:
                fields:
                  - { type: 'tab' , label: 'Основные' }
                  - { property: 'name', label: 'Наименование'}
                  - { type: 'tab' , label: 'Секторы' }
                  - { property: 'background', label: 'Секторы'}
#                  - { property: 'seats', label: 'Места', type: 'collection'}
                  - { property: 'tests1', label: 'Места', type: 'collection'}
        Tickets:
            class: App\Entity\Tickets
            label: 'Билеты'
            list:
                title: 'Билеты'
                fields: ['id', 'name', 'time', 'price']
            form:
                fields:
                  - { type: 'tab' , label: 'Основные' }
                  - { property: 'name', label: 'Наименование'}
                  - { property: 'time', label: 'Время'}
                  - { property: 'price', label: 'Цена'}
        TicketType:
            class: App\Entity\TicketType
            label: 'Типы билетов'
            list:
                title: 'Типы билетов'
                fields: ['id', 'name']
            form:
                fields:
                  - { type: 'tab' , label: 'Основные' }
                  - { property: 'name', label: 'Наименование'}
    design:
        brand_color: 'black'
        menu:
          - Users
          - Events
          - Tickets
          - Hall
          - TicketType
        assets:
            css:
                - '/bundles/lp/css/lp.css'
