version: '2'
services:
    stage_php:
        build: php-fpm
        ports:
            - '9003:9000'
        volumes:
            - ${PWD}:/var/www/symfony
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        links:
            - stage_db
        networks:
            main:
                aliases:
                    - stage_php

    stage_nginx:
        build: nginx
        ports:
            - '8082:80'
            - '1339:1339'
        volumes_from:
            - stage_php
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx/:/var/log/nginx:cached
        networks:
            main:
                aliases:
                    - stage_nginx
    stage_db:
        image: mariadb:latest
        restart: on-failure
        ports:
          - "3311:3306"
        volumes:
          - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
          - ./db:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=stage
          - MYSQL_USER=root
        networks:
            main:
                aliases:
                    - mysql
networks:
    main:
