app_logout:
    path: /logout

cms:
    resource: "Lp/CmsBundle/Resources/config/routing.yaml"

easy_admin_bundle:
    resource: 'App\Controller\AdminController'
    prefix: /admin
    type: annotation





